### ISSUE TITLE
skip path resolution

### ISSUE THREAD

**Issue by tnguyen14** [iarna/require-inject#4]
Is it possible to provide an option that would skip path resolution https://github.com/iarna/require-inject/blob/12ac5b/index.js#L34 ? I have a usecase where I have to mock the behavior of some modules without them being physically there.

**Comment by iarna** [comment]
We do path resolution because the way we inject modules is by fiddling with the require cache directly, and the require cache is keyed on the full path of the modules. Soooo... we have to have a path to inject that that matches up with what node itself produces when you run `require('foobar')`.

(I think you mean https://github.com/iarna/require-inject/blob/12ac5b/index.js#L36 by the way? Line 34 there shouldn't be able to error, it's just doing string manipulations of the path.)

**Comment by tnguyen14** [comment]
Ah I see. Is there any way the keys can be mocked/ added?

And you're right about L36.. There was some reason I reference L34, but I can't remember it now (sorry it's been a while >.<)

**Comment by iarna** [comment]
That's a good question and probably requires reading the `require` and `require.resolved` implementations…

**Comment by iarna** [comment]
So given the way this module works, it can't, really, because it operates by modifying the cache and the cache paths don't exist until the filesystem has been read. To do this requires either replacing `require` or having some infrastructure that Node.js doesn't have. With some luck though, ESM may provide this.
